name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]


env:
  APP_NAME: Typescript GitHub Actions Demo
  APP_ENV: ci
  API_URL: https://api.example.com


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependenices
        run: npm ci

      - name: Print environment variables
        run: |
          echo "APP_NAME: $APP_NAME"
          echo "APP_ENV: $APP_ENV"
          echo "API_URL: $API_URL"

      - name: Build Typescript project
        run: npm run build

      - name: Run unit tests
        run: npm test

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: typescript-build
      #     path: dist

      # - name: Deploy application
      #   run: npm run deploy

      # - name: Upload deployment folder
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: deployment-output
      #     path: deployment-output